# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: 
 branches:
    include:
      - none

pool:
  vmImage: 'ubuntu-latest'
  parameters:
  - name: User
variables:
  - name: User
    value: 'gius.dagostino@reply.it'

jobs:
  - job: maven_build
    displayName: 'Maven Build'
    steps:
      - checkout: self
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          method: 'POST'
          urlSuffix: 'http://130.25.14.49:8085/'
          waitForCompletion: 'false'

  - job: manual_approval
    displayName: "Manual Approval"
    dependsOn: maven_build
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 300
        inputs:
          instructions: "Hi, please take a look at the snyk output and validate or reject according  to the vulnerabilities"
          notifyUsers: 'gius.dagostino@reply.it'
          onTimeout: reject