# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: 
 branches:
    include:
      - none

pool:
  vmImage: 'ubuntu-latest'
  parameters:
  - name: User
variables:
  - name: User
    value: 'gius.dagostino@reply.it'

jobs:
  - job: maven_build
    displayName: 'Maven Build'
    steps:
      - checkout: self
      - task: SnykSecurityScan@1
        inputs:
          serviceConnectionEndpoint: 'Snyk Connection'
          testType: 'app'
          monitorWhen: 'always'
          failOnIssues: false
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          method: 'POST'
          body: |
            Method: POST
            URI: http://130.25.14.49:8085/rest/api/latest/queue/AD-BA?os_authType=basic
            HTTP Version: 1.1
            Headers:
            {
              X-VSS-ActivityId: d5fdd625-37a9-000d-5d80-ef578c27d901
              X-VSS-SubscriptionId: a62a96c4-43ef-4917-861a-c9984f5017d8
              User-Agent: VSServices/19.215.33304.3
              User-Agent: (w3wp.exe)
              Authorization: Basic ********
            }
          urlSuffix: 'http://130.25.14.49:8085/'
          waitForCompletion: 'false'

  - job: manual_approval
    displayName: "Manual Approval"
    dependsOn: maven_build
    pool: server
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 300
        inputs:
          instructions: "Hi, please take a look at the snyk output and validate or reject according  to the vulnerabilities"
          notifyUsers: 'gius.dagostino@reply.it'
          onTimeout: reject

  - job: maven_deploy
    displayName: 'Maven Deploy'
    dependsOn: manual_approval
    steps:
      - task: Maven@3
        displayName: 'Maven pom.xml'
        inputs:
          goals: 'deploy -s settings.xml'
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'
        condition: succeededOrFailed()
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: target
        condition: succeededOrFailed()
  - job: fail
    dependsOn: maven_deploy
    condition: failed()
    #steps:
     #  - publish: '$(System.IncorrectPath)'
  - job: createTask
    displayName: Create Bug On Failure
    dependsOn: fail
    condition: failed()
    steps:
      - template: workitem.yml
        parameters:
          AssignedToUser: $(User)    